### ISSUE TITLE
SOS server is down

### ISSUE THREAD

**Issue by EHJ-52n** [Geonovum/sospilot#20]
Hi there,
the SOS with the URL

    http://sensors.geonovum.nl/sos

is not responding.

Kind regards!

**Comment by justb4** [comment]
Should be up now. Thanks for reminding.

**Comment by EHJ-52n** [comment]
Yes, it is:
http://sensorweb.demo.52north.org/jsClient/?ts=47__geonovum&span=2015-05-29T00:00:00+02:00/2015-05-29T23:59:59+02:00
